_target_: src.models.sennet_hoa_module.SenNetHOAModule

net:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: "efficientnet-b4"
  in_channels: 1
  classes: 2

criterion:
  _target_: segmentation_models_pytorch.losses.DiceLoss
  mode: "binary"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10